name: Adblack_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up time zone
      run: sudo timedatectl set-timezone Asia/Shanghai

    - name: Download Rule
      run: |
        echo ä¸‹è½½anti-AD
        curl -kfSL -o Adblack.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
        echo ä¸‹è½½è‡ªç”¨é»‘åå•
        curl -kfSL -o Blacklist.txt https://raw.githubusercontent.com/mphin/AdGuardHomeRules/main/Blacklist.txt
        echo ä¸‹è½½è‡ªç”¨ç™½åå•
        curl -kfSL -o Allowlist.txt https://raw.githubusercontent.com/mphin/AdGuardHomeRules/main/Allowlist.txt

    - name: Process Rule File
      run: |
        sed -i '/^[#!]/d' Adblack.txt
        echo å¤„ç†é»‘åå•ï¼Œæ·»åŠ è¿›ä¸»è§„åˆ™
        sed -i -e '/^[#!]/d' -e '/^[[:space:]]*$/d' -e 's/[||^@]//g' -e 's/^/DOMAIN-SUFFIX,/' Blacklist.txt
        cat Blacklist.txt >> Adblack.txt
        echo å¤„ç†ç™½åå•ï¼Œåˆ é™¤å¯¹åº”è§„åˆ™
        sed -i -e '/^[#!]/d' -e '/^[[:space:]]*$/d' -e 's/[||^@]//g' -e 's/^/DOMAIN-SUFFIX,/' Allowlist.txt
        while IFS= read -r line; do
          sed -i "/$line/d" Adblack.txt
        done < Allowlist.txt
        echo æ¯”è¾ƒæ–°è§„åˆ™å’Œå·²å­˜åœ¨è§„åˆ™
        if cmp -s Adblack.txt <(sed '/^[#!]/d' "${{ github.workspace }}/rules/Adblack.txt"); then
          echo "æœªæ£€æµ‹åˆ°æ›´æ–°ï¼Œé€€å‡ºå·¥ä½œæµç¨‹"
          exit 0
        fi
        echo æ·»åŠ æ³¨é‡Šæ•°é‡æ—¶é—´å¤‡æ³¨
        version=$(TZ=Asia/Shanghai date '+%Yå¹´%mæœˆ%dæ—¥%H:%M:%S')
        count=$(grep -e '^DOMAIN,' -e '^DOMAIN-SUFFIX,' -e '^IP-CIDR,' -e '^DOMAIN-KEYWORD,' Adblack.txt | wc -l)
        sed -i "1i\\# å†…å®¹: ğŸš« å¹¿å‘Šè¿‡æ»¤ è§„åˆ™é›†\\n# å¤‡æ³¨: ä»¥anti-ADä¸ºåŸºç¡€ï¼Œæ·»åŠ è‡ªç”¨è§„åˆ™ï¼ŒåŸä½œè€…: https://anti-ad.net/\\n# æ›´æ–°: $version\\n# æ•°é‡: $countæ¡" Adblack.txt
        echo åˆ›å»ºDOMAIN-SETæ ¼å¼è§„åˆ™
        cp Adblack.txt Adblack2.txt
        sed -i 's/DOMAIN-SUFFIX,/\./g' Adblack2.txt

        mv Adblack.txt Adblack2.txt rules/

    - name: Commit And Push
      run: |
        git config --global user.email "mphin@qq.com" && git config --global user.name "Bot"
        git add rules/Adblack.txt rules/Adblack2.txt && git commit -m "å¹¿å‘Šè§„åˆ™æ›´æ–°$(date +'%Y-%m-%d %H:%M')" || exit 0
        git push

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2
