name: Adblack_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Rule
      run: |
        echo ä¸‹è½½anti-AD
        curl -o new_surge.txt https://anti-ad.net/surge.txt
        echo ä¸‹è½½è‡ªç”¨é»‘åå•
        curl -o Blacklist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Blacklist.txt
        echo ä¸‹è½½è‡ªç”¨ç™½åå•
        curl -o Allowlist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Allowlist.txt

    - name: Process Rule File
      run: |
        echo å¤„ç†é»‘åå•ï¼Œæ·»åŠ è¿›ä¸»è§„åˆ™
        sed -i -e '/^[#!]/d' -e '/^[[:space:]]*$/d' -e 's/||\|^@//g' -e 's/\^//g' -e 's/^/DOMAIN-SUFFIX,/' Blacklist.txt
        cat Blacklist.txt >> new_surge.txt
        
        echo å¤„ç†ç™½åå•ï¼Œåˆ é™¤å¯¹åº”è§„åˆ™
        awk '/^[^!#]/{print "DOMAIN-SUFFIX,"$1}' Allowlist.txt > allowlist.txt
        sed -i 's/\^//g' allowlist.txt
        while IFS= read -r line; do
          sed -i "/$line/d" new_surge.txt
        done < allowlist.txt
        
        echo æ·»åŠ æ³¨é‡Šæ•°é‡æ—¶é—´å¤‡æ³¨
        sed -i '/^[#!]/d' new_surge.txt
        new_version=$(TZ=Asia/Shanghai date '+%Yå¹´%mæœˆ%dæ—¥%H:%M:%S')
        rule_count=$(grep -E 'DOMAIN-SUFFIX' new_surge.txt | wc -l)
        sed -i "1i\\# å†…å®¹: ðŸš« å¹¿å‘Šè¿‡æ»¤ è§„åˆ™é›†\\n# å¤‡æ³¨: ä»¥anti-ADä¸ºåŸºç¡€ï¼Œç§»é™¤è‡ªç”¨è¯¯æ€ï¼Œå¢žåŠ è‡ªç”¨é»‘åå•ï¼ŒåŽŸä½œè€…: https://github.com/privacy-protection-tools/anti-AD\\n# æ›´æ–°: $new_version\\n# æ•°é‡: $rule_countæ¡" new_surge.txt
     
        echo åˆ›å»ºDOMAIN-SETæ ¼å¼è§„åˆ™
        cp new_surge.txt new_surge2.txt
        sed -i 's/DOMAIN-SUFFIX,/\./g' new_surge2.txt

        mv new_surge.txt rules/Adblack.txt
        mv new_surge2.txt rules/Adblack2.txt

    - name: Commit And Push
      run: |
        git config --global user.email "long632450362@qq.com" && git config --global user.name "Bot"
        git add rules/Adblack.txt rules/Adblack2.txt && git commit -m "è‡ªåŠ¨æ›´æ–°å¹¿å‘Šæ‹¦æˆªè§„åˆ™"
        git push

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2
