name: Update Adblack File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update-surge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download New Version of anti-AD
      run: |
        curl -o new_surge.txt https://anti-ad.net/surge.txt

    - name: Download 777 Blacklist
      run: |
        curl -o 777_Blacklist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Blacklist.txt

    - name: Download 777 Allowlist
      run: |
        curl -o 777_Allowlist.txt https://raw.githubusercontent.com/mphin/AdGuardHome_rules/main/777_Allowlist.txt

    - name: Add Blacklist
      run: |
        sed -i -e '/^[#!]/d' -e 's/||\|^@//g' -e 's/\^//g' -e 's/^/DOMAIN-SUFFIX,/' 777_Blacklist.txt
        cat 777_Blacklist.txt >> new_surge.txt

    - name: Remove Blacklist Based on Whitelist
      run: |
        awk '/^[^!#]/{print "DOMAIN-SUFFIX,"$1}' 777_Allowlist.txt > allowlist.txt
        while IFS= read -r line; do
          sed -i "/$line/d" new_surge.txt
        done < allowlist.txt

    - name: Remove Original Comments, Add New Comments
      run: |
        sed -i '/^[#!]/d' new_surge.txt
        new_version=$(TZ=Asia/Shanghai date '+%Yå¹´%mæœˆ%dæ—¥%H:%M:%S')
        rule_count=$(grep -E 'DOMAIN-SUFFIX' new_surge.txt | wc -l)
        sed -i "1i\\# å†…å®¹: ðŸš« å¹¿å‘Šè¿‡æ»¤ è§„åˆ™é›†\\n# å¤‡æ³¨: ä»¥anti-ADä¸ºåŸºç¡€ï¼Œç§»é™¤è‡ªç”¨è¯¯æ€ï¼Œå¢žåŠ è‡ªç”¨é»‘åå•ï¼Œanti-ADä½œè€…: https://github.com/privacy-protection-tools/anti-AD\\n# æ›´æ–°: $new_version\\n# æ•°é‡: $rule_countæ¡" new_surge.txt

    - name: Replace old Surge.txt with modified version
      run: |
        mv new_surge.txt Adblack.list
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Adblack.list
        git commit -m "Update Adblack.list"
        git push
